version: "3"

services:
  mysql:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    container_name: sql-2
    environment:
      MYSQL_ROOT_PASSWORD: c1vG7R34
      MYSQL_DATABASE: admin
      MYSQL_USER: digitalman
      MYSQL_PASSWORD: c1vG7R34
      TZ: Asia/Kuala_Lumpur
    ports:
      - "3800:3306"

volumes:
  db_data:
